// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drokklpujlrnoelfmilj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyb2trbHB1amxybm9lbGZtaWxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDk1NjIsImV4cCI6MjA1NTQ4NTU2Mn0.Q3raA198PHrquCWmOgsYANBgJZuC9KuW3Cu5uy9SfNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);